apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::199111494326:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-UVVSE881B66Y
      username: system:node:{{EC2PrivateDNSName}}
    -groups:
      - system:masters
      roleearn: arn:aws:iam::199111494326:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-08T17:41:37Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "16163"
  uid: 7e1942b2-741f-4ec7-aa84-60be1eed8b4c
